name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 0 * * 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node: 12.x
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run -s lint

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [6.x, 8.x, 10.x, 12.x]
        eslint: [4.x, 5.x, 6.x]
        exclude:
          - node: 6.x
            eslint: 4.x
          - node: 6.x
            eslint: 5.x
          - node: 8.x
            eslint: 4.x
          - node: 8.x
            eslint: 5.x
          - node: 10.x
            eslint: 4.x
          - node: 10.x
            eslint: 5.x

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node: ${{ matrix.node }}
    - name: Install Packages
      run: npm install && npm install --no-save eslint@${{ matrix.eslint }}
    - name: Test
      run: npm run -s test:mocha
    - name: Send Coverage
      run: npm run -s codecov
