name: Website
on:
  push:
    tags: ["v*"]

jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node: 12.x
    - name: Install Packages
      run: npm install
    - name: Build
      run: npm run -s docs:build
    - name: Deploy
      run: |
        cd docs/.vuepress/dist
        git init
        git push -f https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git master:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
